### ISSUE TITLE
Ubuntu 22.04 NoneType error

### ISSUE THREAD

**Issue by ugorur** [Rudd-O/homeassistant-hassmpris#1]
Traceback (most recent call last):
  File "/home/bixos/.local/bin/hassmpris-agent", line 5, in <module>
    from hassmpris_agent.server import main
  File "/home/bixos/.local/lib/python3.10/site-packages/hassmpris_agent/server.py", line 15, in <module>
    from hassmpris_agent.mpris.grpc import MPRISServer  # noqa: E402
  File "/home/bixos/.local/lib/python3.10/site-packages/hassmpris_agent/mpris/grpc.py", line 29, in <module>
    from hassmpris.proto import mpris_pb2_grpc, mpris_pb2
  File "/home/bixos/.local/lib/python3.10/site-packages/hassmpris/proto/mpris_pb2_grpc.py", line 6, in <module>
    from hassmpris.proto import mpris_pb2 as mpris__pb2
  File "/home/bixos/.local/lib/python3.10/site-packages/hassmpris/proto/mpris_pb2.py", line 21, in <module>
    _PLAYERSTATUS = DESCRIPTOR.enum_types_by_name['PlayerStatus']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'

Linux 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ugorur** [comment]
`pip3 install --upgrade protobuf` solved my issue

**Comment by Rudd-O** [comment]
Thank you, but it's strange, protobuf should be required.  Which protobuf version did you have before and which version did you install?

**Comment by ugorur** [comment]
i don't remember old version but current version is: `Version: 4.24.4`
This error come from agent. I opened this in wrong repo.
